=== RickWayne/R2CSharpConsoleApp/RUSLE2/RomeAPI/RomeSDK(2.6.2.2)Docs/Docs/catalog.dtd
<!--
 External DTD for validating XML catalogs used by Rusle2.
 The XML "catalog" defines the elements of the scientific model.
 It is loaded on application startup, either from a binary resource or a compiled-in string constant.
 Instances are created at runtime from these catalog listing entries.
 The catalog doesn't specify the appearance of the model - that is specified by user templates.
 The structure of the catalog XML document largely mirrors that of the XML data files described in "data.dtd".

 The following DOCTYPE entry is only used in an internal DTD.
 <!DOCTYPE Catalog [
-->

    <!-- The "Catalog" is the description of the scientific model.
         Model   - A named subcomponent of the full model.
		             For historical reasons the is divided into the "shared" model,
                     which contains generic model parameters, and the "RUSLE2" model.
                     This attribute is not currently used when read.
         Science - This is a decimal version number in format YYYYMMDD.
                     It represents the time of the last signifigant science change.
                     It may remain the same between different minor Rusle2 versions.
      -->
    <!ELEMENT Catalog (Objects | Obj | Sub | CalcFns | InterlockFns | Comment)* >
    <!ATTLIST Catalog Model     NMTOKEN #IMPLIED
                      Science   NMTOKEN #IMPLIED >

    <!-- The "Objects" collection list all object types recognized by the model.
         This _declares_ the objects, before they are _defined_ individually below.
         It may contain any number of "Obj" or "Sub" entries.
         The "Group" elements are used to group the other elements by object type.
      -->
    <!ELEMENT Objects (Obj | Sub | Group | Comment)*>

    <!-- Custom entity for the different elements used by parameter definitions.
	     This is useful because any parameter type may be contained in any object type.
      -->
    <!ENTITY % ParamTags "Bit | Bol | Dte | Flt | Int | Lst | ObR | Ovr | Pic | RmtUp | Rmt | SbR | Sta | Str" >

    <!-- An "Obj" is a _file_ level object. It may generally be saved in the database.
	     It behaves almost identically to a "Sub" object, which may not be save directly in the database.
		 "Obj" objects are generally declared at global scope in this DTD.
		 "Sub" objects are generally declared inside the object type that they are used in.
		   This is a convention, and not used by the loading code. In fact, many subobjects may
		   do not have a unique object type that they are used in.
		 All parameters contained in an object must be defined inside the object's definition.
		   It is not valid to define a parameter more than once though, so the element <AllowAttr>
		   can be used in other object definitions to declare that it can occur in them.
         Name    The internal Rusle2 name for the object type (e.g. "CLIMATE").
         Ext     A file extension (for internal use, and for exported XML files).
         Bit     The name of the bitmap to use for this object type.
                 This has format "res://bitmap-name" for internal (resource) bitmaps.
                 For external bitmaps it is a filename relative to the Rusle2\Users directory.
                 Bitmap names (the part after "res://") and filenames are case-insensitive.
         Btn     The resource ID of the toolbar button for this object type.
                 This should be 0 for non-file objects that don't show on the toolbar.
         Table   The database table name used to store this object type (e.g. "climates")
         Flags   Flags of type enum ObjTypeFlags. Default value is OBJT_NONE.
                 Flags are separated by whitespace and | characters.
      -->
    <!ELEMENT Obj (Sub | AllowAttr|StartFn|CleanupFn | CalcFn|InterlockFn|ValFn|ForceUniquePointers | Comment|Group|r2if | Flags|Choices | %ParamTags;)* >
    <!ATTLIST Obj   Name    CDATA   #REQUIRED
                    Ext     CDATA    #IMPLIED
                    Bit     CDATA    #IMPLIED
                    Btn     CDATA    #IMPLIED
                    Table   CDATA    #IMPLIED
                    Flags   CDATA    #IMPLIED
    >

    <!-- A subobject is an object type that cannot be saved directly in the database.
	     (See comments for the "Obj" element.)
      -->
    <!ELEMENT Sub (Sub | AllowAttr|StartFn|CleanupFn | CalcFn|InterlockFn|ValFn|ForceUniquePointers | Comment|Group|r2if | Flags|Choices | %ParamTags;)* >
    <!ATTLIST Sub   Name    CDATA   #REQUIRED
                    Flags   CDATA    #IMPLIED >

    <!-- This element is a proxy for "xsl:if", which we will eventually replace it with. -->
    <!ELEMENT r2if ANY>
    <!ATTLIST r2if test CDATA #REQUIRED >

    <!-- ******************************************************************* -->

    <!-- Allow a parameter to occur in a diferent [sub]object.
      This is used to declare promoted parameters, and to share the definition
      of parameters which are used in multiple subobjects of similar types.
      -->
    <!ELEMENT AllowAttr EMPTY >
    <!ATTLIST AllowAttr
        Attr    CDATA    #IMPLIED
    >

    <!-- This is used to comment-out parts of the catalog.
	     These comments elements can nest, which normal XML comments can't.
	  -->
    <!ELEMENT Comment   ANY >

    <!-- Each object type may have a single _start function_.
	     This function is run on object creation to initialize it.
         The Rusle2 computational engine performs lazy evaluation based on
		   changes to parameters which are declared to be "terms" of a calc function.
		 Normally, a visual in the graphical user interface causes the creation of a parameter,
		   which in turns run its calc function, and builds these term relationships.
		 The start function allows building these term relationships in the absence of a visual interface.
	  -->
    <!ELEMENT StartFn   EMPTY >
    <!ATTLIST StartFn
        Name    CDATA   #REQUIRED
    >

    <!-- A _cleanup function_ is run on loading a saved data file.
	  -->
    <!ELEMENT CleanupFn ANY >
    <!ATTLIST CleanupFn
        Attr    CDATA    #IMPLIED
        Name    CDATA   #REQUIRED
        Code    CDATA    #IMPLIED
    >

    <!-- An _interlock_function_ is used to enforce a constraint on a set of parameters.
	     The standard example is the set SAND,SILT,CLAY, which must add up to 1.
		 Each parameter may have a single [optional] interlock function.
		 No parameter may belong to more than one interlock function.
		 An interlock function will generally be declared for all parameters that it affects.
		 A parameter by have both a calc function and an interlock function.
		 Attr - The name of the parameter to which this function is being added.
		        If the Attr attribute isn't present, it is assumed to be the parameter
				whose definition immediately precedes the function's definition.
		 Name - The internal name (identifier) of the function.
		 Code - The name of the function implementation in the C++ code.
	  -->
    <!ELEMENT InterlockFn (Param*) >
    <!ATTLIST InterlockFn
        Attr    CDATA    #IMPLIED
        Name    CDATA   #REQUIRED
        Code    CDATA    #IMPLIED
        Flags   CDATA    #IMPLIED
   >

    <!-- A _validation_function_ is used to enforce constraints user input to a parameter.
		 Each parameter may have a single [optional] validation function.
		 Attr - The name of the parameter to which this function belongs.
		        If the Attr attribute isn't present, it is assumed to be the parameter
				whose definition immediately precedes the function's definition.
		 Name - The internal name (identifier) of the function.
		 Code - The name of the function implementation in the C++ code.
	  -->
    <!ELEMENT ValFn EMPTY >
    <!ATTLIST ValFn
        Attr    CDATA    #IMPLIED
        Name    CDATA   #REQUIRED
        Code    CDATA    #IMPLIED
    >

    <!-- A _calc_function_ is the basic unit of computation in Rusle2.
		 Each parameter may have a single [optional] calc function.
		 A parameter by have both a calc function and an interlock function.
		 Attr - The name of the parameter which this function has as an output.
		        If the Attr attribute isn't present, it is assumed to be the parameter
				whose definition immediately precedes the function's definition.
		 Name - The internal name (identifier) of the function.
		 Code - The name of the function implementation in the C++ code.
	  -->
    <!ELEMENT CalcFn ANY >
    <!ATTLIST CalcFn
        Attr    CDATA    #IMPLIED
        Name    CDATA   #REQUIRED
        Code    CDATA    #IMPLIED
    >

    <!-- "ObR" parameters hold filenames, and are usually allowed to contain duplicates.
	     If this element is declared for a parameter, then it is NOT allowed to contain
		 duplicate entries. When a duplicate entry would be inserted, that file cloned instead.
		 Attr - The name of the parameter to declare as having unique pointers.
	  -->
    <!ELEMENT ForceUniquePointers   EMPTY >
    <!ATTLIST ForceUniquePointers
        Attr    CDATA   #REQUIRED
    >

    <!-- ******************************************************************* -->

    <!-- The "InterlockFns" collection lists interlock functions used by the model.
         This _declares_ the functions, before they are added for individually parameters below.
		 (Declaring an interlock function in this element is currently optional.)
         The "Group" elements are currently just used to group the other elements for documentation purposes.
      -->
    <!ELEMENT InterlockFns (InterlockFn | Group|Comment)* >

    <!-- The "CalcFns" collection lists calc functions used by the model.
         This _declares_ the functions, before they are added for individually parameters below.
         The "Group" elements are used to group the other elements by object type.
      -->
    <!ELEMENT CalcFns      (Fn | Group|Comment)* >

    <!-- A _calc_function_ is the basic unit of computation in Rusle2.
	     This element declares a calc function before it is associated with a parameter.
		 Each parameter may have a single [optional] calc function.
		 Attr - The name of the parameter which this function has as an output.
		        If the Attr attribute isn't present, it is assumed to be the parameter
				whose definition immediately precedes the function's definition.
		 Name - The internal name (identifier) of the function.
		 Code - The name of the function implementation in the C++ code.
		 Flag - Named flags which modify the functions behavior.
	  -->
    <!ELEMENT Fn          (Terms?, Affecteds?, Param*) >
    <!ATTLIST Fn
        Attr    CDATA    #IMPLIED
        Name    NMTOKEN #REQUIRED
        Code    CDATA    #IMPLIED
        Flags   CDATA    #IMPLIED
    >

	<!-- These are collections used to group the corresponding singular elements. -->
    <!ELEMENT Affecteds (Affected*) >
    <!ELEMENT Terms     (Term*) >

    <!ELEMENT Affected  (#PCDATA) >
    <!ELEMENT Term      (#PCDATA) >

    <!ELEMENT Param     EMPTY>
    <!ATTLIST Param
        Name    NMTOKEN #REQUIRED
    >

    <!-- ******************************************************************* -->

    <!-- "Group" elements are used to group other elements by object type. -->
    <!ELEMENT Group     ANY >
    <!ATTLIST Group
        Obj     CDATA    #IMPLIED
        Sub     CDATA    #IMPLIED
    >

    <!-- This element lists flags used to modify behavior of a parameter.
       ACF_NO_USER_SIZE   - User can't resize (the program may)
	   ACF_NO_USER_EDIT   - User can't edit (the program may)
	   ACF_INTEGRAL       - This is an integer (was a display flag in visual pref)
	   ACF_ALLOW_NONE     - Allow entry ENTRY_NONE, "(none)" by user
	   ACF_ALLOW_CUSTOM   - Allow value ENTRY_CUSTOM, "(custom)", only set by code
	   ACF_NO_SET_CHANGED - Doesn't set the file dirty if param changes.
	   ACF_NO_NAN         - Don't allow entry NaN (which is empty string for some parameters)
	   ACF_ALLOW_INTERNAL - Allow value ENTRY_INTERNAL, "(internal)", which allows using internal files
	  -->
    <!ELEMENT Flags     ANY>

    <!-- Lists a finite set of named string values that a parameter can take on.
		 It contains a comma-separated list of double-quoted names.
	     Used by "Lst" elements (list parameters) to list legal values.
	     Used by "SbR" elements (subobject parameters) to list legal object types.
		 Attr - The name of the parameter which this list applies to.
	  -->
    <!ELEMENT Choices   ANY>
    <!ATTLIST Choices   Attr    CDATA    #IMPLIED >

    <!-- ******************************************************************* -->
    <!-- Parameter Defintions
      These tags are the same as those save in Rusle2 xml data files.
     -->

    <!ELEMENT Bit   EMPTY> <!-- Bitmap   -->
    <!ELEMENT Bol   EMPTY> <!-- Boolean  -->
    <!ELEMENT Dte   EMPTY> <!-- Date     -->
    <!ELEMENT Flt   EMPTY> <!-- Float    -->
    <!ELEMENT Int   EMPTY> <!-- Integer  -->
    <!ELEMENT Lst   EMPTY> <!-- List     -->
    <!ELEMENT ObR   EMPTY> <!-- Pointer  -->
    <!ELEMENT Ovr   EMPTY> <!-- Override -->
    <!ELEMENT Pic   EMPTY> <!-- Picture  -->
    <!ELEMENT Rmt   EMPTY> <!-- Remote   -->
    <!ELEMENT SbR   EMPTY> <!-- SubPtr   -->
    <!ELEMENT Sta   EMPTY> <!-- Static   -->
    <!ELEMENT Str   EMPTY> <!-- String   -->

    <!-- This tag is used to declare a "remote up", which is an abbreviated
         form for declaring a remote parameter <Rmt>.
      -->
    <!ELEMENT RmtUp EMPTY>

	<!-- Attributes shared by the parameter definitions:
	     (Not all attributes are legal in all parameter elements.)
	     Name    - name (identifier) of the parameter.
		 Fn      - name of the parameter's calc function. (can be empty)
		 Unit    - name of the parameter's default unit.  (can be empty)
		 Default - default value for this parameter.
		 Min     - minimum legal value for this parameter.
		 Max     - maximum legal value for this parameter.
		 Obj     - object type for a pointer parameter.
		 RemAttr - name of the remote parameter pointed to.
		 PtrAttr - name of the pointer parameter to remote through.
		 d0      - name of the parameter's 1st dimension. (can be empty)
		 d1      - name of the parameter's 2nd dimension. (can be empty)
	  -->

    <!-- Parameter Attributes -->
    <!ATTLIST Bit
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #IMPLIED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST Bol
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #IMPLIED
        Default CDATA    #IMPLIED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST Dte
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #IMPLIED
        Min     CDATA   #REQUIRED
        Max     CDATA   #REQUIRED
        Default CDATA   #REQUIRED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST Flt
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #IMPLIED
        Min     CDATA   #REQUIRED
        Max     CDATA   #REQUIRED
        Default CDATA   #REQUIRED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST Int
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #IMPLIED
        Min     CDATA   #REQUIRED
        Max     CDATA   #REQUIRED
        Default CDATA   #REQUIRED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST Lst
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #IMPLIED
        Default CDATA    #IMPLIED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST ObR
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #FIXED     ""
        Default CDATA    #IMPLIED
        Obj     CDATA   #REQUIRED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST Ovr
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        RemAttr CDATA   #REQUIRED
        PtrAttr CDATA   #REQUIRED
        d0      CDATA    #IMPLIED
    >

    <!ATTLIST Pic
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #FIXED     ""
        Default CDATA    #IMPLIED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST Rmt
        Name    CDATA   #REQUIRED
        Fn      CDATA    #FIXED     ""
        RemAttr CDATA   #REQUIRED
        PtrAttr CDATA   #REQUIRED
    >

    <!ATTLIST RmtUp
        Name    CDATA   #REQUIRED
        RemAttr CDATA   #REQUIRED
    >

    <!ATTLIST SbR
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Default CDATA   #REQUIRED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

    <!ATTLIST Sta
        Name    CDATA   #REQUIRED
    >

    <!ATTLIST Str
        Name    CDATA   #REQUIRED
        Fn      CDATA    #IMPLIED
        Unit    CDATA    #IMPLIED
        Default CDATA    #IMPLIED
        d0      CDATA    #IMPLIED
        d1      CDATA    #IMPLIED
    >

<!--
 The following close delimiter is only used in internal DTDs.
 ]>
-->

=== RickWayne/R2CSharpConsoleApp/RUSLE2/RomeAPI/RomeSDK(2.6.2.2)Docs/Docs/catalog.shared.xml
<?xml version="1.0" standalone="no" ?>

<!-- Use an external DTD to validate this XML document. -->
<!DOCTYPE Catalog SYSTEM "catalog.dtd"
  [
	<!--
	Define symbolic constants used by the catalog.
	These generally come from symbols defined in "resource.h" and "model.h".
	These are NOT automatically updated when the symbols defined in the header change!
	-->
	<!ENTITY ID_DATA_COEFF		'9004'>
	<!ENTITY ID_DATA_LIMITS		'9102'>
	<!ENTITY ID_DATA_CLIMATE	'306'>
	<!ENTITY ID_DATA_MANAGEMENT	'307'>
	<!ENTITY ID_DATA_OPERATION	'302'>
	<!ENTITY ID_DATA_RESIDUE	'304'>
	<!ENTITY ID_DATA_SLOPE		'305'>
	<!ENTITY ID_DATA_SOIL		'301'>
	<!ENTITY ID_DATA_VEGETATION	'303'>
	<!ENTITY ID_DATA_STRUCTURE	'310'>

  ]
>

<!--
 Catalog entries for the Rusle2 catalog.
 These largely follow the format of saved Rusle2 files, to make processing easier.
 The parameters for each object are placed inside the <Obj> or <Sub> element for that object type.
   Note, however, that some parameters can occur in multiple objects when they are promoted.
   The <AllowAttr ...> element is used to declare attrs that are defined in another [sub]object.
 In the runtime catalog implementation all parameter listings are held by a single data structure the same level.

 This XML "catalog" defines the complete scientific model structure.
 It is loaded once on application startup, to create "listings" for object/parameter definitions.
 Instances are created at runtime from these catalog listing entries.
 The catalog doesn't specify the appearance of the model - that is specified by user templates.

 Copyright (C) 1994-2005 University of Tennessee.
 All rights reserved.
-->

<!--
  SCIENCEVERSION
  The following science versions must be in synch:
  - the science version in the ScienceChange array SharedScienceChanges[].
  - the science version in DefineSharedModel().
  - the science version in "catalog.shared.xml".
-->

<Catalog Model="shared" Science="20090107">


<Objects>
	<!-- Define [file] object types:
		The bitmap ID is a string of the form "res://bitmap-name" for internal (resource) bitmaps.
		The [toolbar] button ID "Btn" is an integer defined in "resource.h". It is defined above in the inline DOCTYPE for this file.
		See "catalog.dtd" for a full descripton of the attribute values.
	-->
	<Obj Name="COEFFICIENTS"		Ext="coe"		Bit="res://bit_coe.bmp"		Btn="&ID_DATA_COEFF;"		Table="no path coeff"	Flags="OBJT_BUILTIN | OBJT_ISFILE"/>
	<Obj Name="CONSTANTS"			Ext=""			Bit=""						Btn="0"						Table="constants"		Flags="OBJT_BUILTIN | OBJT_ISFILE"/>
	<Obj Name="LIMITS"				Ext="lim"		Bit="res://bit_lim.bmp"		Btn="&ID_DATA_LIMITS;"		Table="limits"/>

	<Obj Name="CLIMATE"				Ext="cli"		Bit="res://bit_cli.bmp"		Btn="&ID_DATA_CLIMATE;"		Table="climates"/>
	<Obj Name="MANAGEMENT"			Ext="man"		Bit="res://bit_man.bmp"		Btn="&ID_DATA_MANAGEMENT;"	Table="managements"/>
	<Obj Name="OPERATION"			Ext="ope"		Bit="res://bit_ope.bmp"		Btn="&ID_DATA_OPERATION;"	Table="operations"/>
	<Obj Name="RESIDUE"				Ext="rsd"		Bit="res://bit_rsd.bmp"		Btn="&ID_DATA_RESIDUE;"		Table="residues"/>
	<Obj Name="SLOPE"				Ext="pro"		Bit="res://bit_pro.bmp"		Btn="&ID_DATA_SLOPE;"		Table="profiles"/>
	<Obj Name="SOIL"				Ext="soi"		Bit="res://bit_soi.bmp"		Btn="&ID_DATA_SOIL;"		Table="soils"/>
	<Obj Name="VEGETATION"			Ext="veg"		Bit="res://bit_veg.bmp"		Btn="&ID_DATA_VEGETATION;"	Table="vegetations"/>
<!--<Obj Name="STRUCTURE_BARRIER"	Ext="stc"		Bit="res://bit_stc.bmp"		Btn="&ID_DATA_STRUCTURE;"	Table="structures-barriers"/> -->

	<Obj Name="GUI_ACCESS"			Flags="OBJT_UNIQUE"/>
</Objects>


<Obj Name="CONSTANTS">
	<Dte Name="DAYS_IN_YEAR"			Fn="FN_INDEX_DAYS_IN_YEAR"	Unit="U_MMDD"			Min="0" Default="0" Max="365"	d0="365"/>
		<Flags>ACF_NO_USER_SIZE | ACF_NO_USER_EDIT</Flags>
<!--<Flt Name="HALF_MONTH"				Fn="FN_INDEX_FROM_ONE"		Unit=""					Min="1" Default="1" Max="24"	d0="24"/> -->
	<Str Name="HALF_MONTH_STR"			Fn="FN_HALF_MONTH"			Unit=""					Default=""			d0="24"/>
		<Flags>ACF_NO_USER_SIZE | ACF_NO_USER_EDIT</Flags>
	<Str Name="MONTHS"					Fn="FN_MONTHS"				Unit=""					Default=""			d0="12"/>
		<Flags>ACF_NO_USER_SIZE | ACF_NO_USER_EDIT</Flags>
</Obj>

<Obj Name="CLIMATE">
	<Str Name="CLI_DESCRIP"/>
	<Flt Name="ELEV"					Fn=""						Unit="U_FOOT"			Min="-1000" Default="1000" Max="50000"/>
	<Flt Name="FREEZE_FREE"				Fn=""						Unit="U_DAYS"			Min="0" Default="200" Max="365"/>
		<Flags>ACF_NO_USER_SIZE | ACF_NO_USER_EDIT</Flags>
</Obj>


<Obj Name="GUI_ACCESS">
	<Sta Name="GUI_REDO"/>
	<Sta Name="GUI_UNDO"/>
	<Sta Name="GUI_LOAD_TEMPLATE"/>
	<Sta Name="GUI_EDIT_TEMPLATE"/>
	<Sta Name="GUI_SAVE_TEMPLATE"/>

	<Sta Name="GUI_DB_COMPARE"/>
	<Sta Name="GUI_DB_COMPACT"/>
	<Sta Name="GUI_DB_CHECK"/>
	<Sta Name="GUI_DB_REARRANGE"/>
	<Sta Name="GUI_DB_IMPORT_R1"/>
	<Sta Name="GUI_DB_IMPORT_R2"/>
	<Sta Name="GUI_DB_EXPORT_R2"/>
	<Sta Name="GUI_DB_IMPORT_FILE"/>
	<Sta Name="GUI_DB_EXPORT_FILE"/>
	<Sta Name="GUI_DB_REPAIR"/>
	<Sta Name="GUI_DB_STARTUP"/>
	<Sta Name="GUI_DB_IMPORT_NZ_RAIN"/>

	<Sta Name="GUI_FILE_IMPORT"/>
	<Sta Name="GUI_FILE_EXPORT"/>

	<Sta Name="GUI_FILE_IMPORT_NRCS"/>
	<Sta Name="GUI_FILE_IMPORT_RUSLE2"/>
  <Sta Name="GUI_FILE_IMPORT_NASIS_SOIL"/>
  <Sta Name="GUI_FILE_IMPORT_SSURGO_SOIL"/>
  <Sta Name="GUI_FILE_IMPORT_SSURGO_SOIL_DETAIL"/>
	<Sta Name="GUI_FILE_IMPORT_USDA_CLIMATE"/>

	<Sta Name="GUI_FILE_EXPORT_FILESET"/>
	<Sta Name="GUI_FILE_EXPORT_NRCS"/>
	<Sta Name="GUI_FILE_EXPORT_RUSLE2"/>

	<Sta Name="GUI_FILE_CLONE"/>
	<Sta Name="GUI_FILE_APPLY_PARAM"/>

	<Sta Name="GUI_TOOLS_DUMP_WEB"/>
	<Sta Name="GUI_TOOLS_VALIDATE_REPORTS"/>

	<Sta Name="GUI_ADMIN_ACCESS_SAVE_TEXT"/>
<!--<Sta Name="GUI_ADMIN_PERMS_LOAD_TEXT"/> -->
<!--<Sta Name="GUI_ADMIN_PERMS_SAVE_TEXT"/> -->


	<!--
	 This controls how much the user can use MDBS:
	 HIDE: can't use or see at all.
	 SEE:  import only, do diffs,...
	 EDIT: load, run, save.
	-->
	<Sta Name="GUI_MDB_ACCESS"/>


	<!--
	 This controls whether/not the user can edit the base attr
	 when an overridden value is present for it in an open file.
	 HIDE: hide cell (UNIMPLEMENTED)
	 SEE:  show cell as readonly.
	 EDIT: allow editing even when overridden.
	-->
	<Sta Name="GUI_OVERRIDE_BASE"/>

	<!--
	 This controls whether/not to show override attrs with special visuals.
	 HIDE: don't show extra visual indicator
	 SEE:  show extra indicator
	 EDIT: show indicator and allow using to change status.
	-->
<!--<Sta Name="GUI_OVERRIDE_VISUAL"/> -->

</Obj>


<Obj Name="MANAGEMENT">
</Obj>


<Obj Name="OPERATION">
	<Str Name="OP_DESCRIP"/>
	<Flt Name="OP_SPEED_MIN"			Fn=""					Unit="U_MILES_P_HR"	Min="0" Default="3" Max="20"/>
	<Flt Name="OP_SPEED_MAX"			Fn=""					Unit="U_MILES_P_HR"	Min="0" Default="8" Max="20"/>
	<Flt Name="OP_SPEED"				Fn=""					Unit="U_MILES_P_HR"	Min="0" Default="4" Max="20"/>
</Obj>


<Obj Name="RESIDUE">
	<Str Name="RES_DESCRIP"/>
</Obj>


<Obj Name="SLOPE">
	<Str Name="SLOPE_DESCRIP"/>
	<ObR Name="CLIMATE_PTR"				Fn=""					Unit=""			Default="#ENTRY_DEFAULT"	Obj="CLIMATE"/>
</Obj>


<Obj Name="SOIL">
	<Str Name="SOIL_DESCRIP"			Default=" "/>
	<Flt Name="ORGANIC_MATTER"			Fn=""					Unit="U_PERCENT"	Min="0" Default="2.5" Max="100"/>
  <Flt Name="ORGANIC_MATTER_HIGH"			Fn=""					Unit="U_PERCENT"	Min="0" Default="2.5" Max="100"/>
  <Flt Name="ORGANIC_MATTER_LOW"			Fn=""					Unit="U_PERCENT"	Min="0" Default="2.5" Max="100"/>
  <Lst Name="PERMEABILITY"			Fn=""					Unit=""				Default="PERMEABILITY_SLOW_TO_MOD"/>
		<Choices Attr="PERMEABILITY">"PERMEABILITY_RAPID", "PERMEABILITY_MOD_TO_RAPID", "PERMEABILITY_MOD",
						"PERMEABILITY_SLOW_TO_MOD", "PERMEABILITY_SLOW", "PERMEABILITY_VERY_SLOW"</Choices>
	<Bit Name="SOIL_GRAPHIC"			Fn="FN_SOIL_GRAPHIC"/>
</Obj>


<Obj Name="VEGETATION">
	<Str Name="VEG_DESCRIP"/>
<!--	<ObR Name="VEG_RES"					Fn=""					Unit=""				Default="#ENTRY_DEFAULT"	Obj="RESIDUE"/> -->
	<ObR Name="VEG_ROOT_RES"			Fn=""					Unit=""				Default="#ENTRY_DEFAULT"	Obj="RESIDUE"/>
</Obj>


<CalcFns>
	<Fn Name="FN_INDEX_FROM_ONE"			Code="FnIndexFromOne"		Flags="FNF_FORCE_AUTOUPDATE | FNF_PROMOTABLE"/>
	<Fn Name="FN_MONTHS"					Code="FnMonths"/>
<!--	<Fn Name="FN_DAILY_TEMP"				Code="FnDailyTemp"/> -->
<!--	<Fn Name="FN_DAILY_PRECIP"				Code="FnDailyPrecip"/> -->
	<Fn Name="FN_MAN_GRAPHIC"				Code="FnManGraphic"/>
	<Fn Name="FN_SOIL_GRAPHIC"				Code="FnSoilGraphic"/>
</CalcFns>


</Catalog>
